/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExamLevel = IDL.Variant({
  'Purna' : IDL.Null,
  'Year1' : IDL.Null,
  'Year2' : IDL.Null,
  'Year3' : IDL.Null,
  'Year4' : IDL.Null,
  'Year5' : IDL.Null,
  'Year6' : IDL.Null,
  'Year7' : IDL.Null,
  'Year8' : IDL.Null,
  'Adhya' : IDL.Null,
  'Madhya' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Artwork = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'artistId' : IDL.Text,
  'level' : ExamLevel,
  'image' : ExternalBlob,
  'isPublic' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Int,
});
export const Exam = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Int,
  'level' : ExamLevel,
  'score' : IDL.Nat,
});
export const StudentView = IDL.Record({
  'id' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'name' : IDL.Text,
  'artwork' : IDL.Opt(ExternalBlob),
  'level' : ExamLevel,
  'exams' : IDL.Vec(Exam),
  'guardian' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveAdmission' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getArtwork' : IDL.Func([IDL.Text], [IDL.Opt(Artwork)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPublicArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(StudentView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'promoteStudent' : IDL.Func([IDL.Text, ExamLevel], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchStudentsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentView)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Text], [], []),
  'submitAdmissionForm' : IDL.Func(
      [IDL.Text, IDL.Text, ExamLevel, ExternalBlob],
      [IDL.Text],
      [],
    ),
  'uploadArtwork' : IDL.Func(
      [IDL.Text, IDL.Text, ExamLevel, IDL.Bool, ExternalBlob],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExamLevel = IDL.Variant({
    'Purna' : IDL.Null,
    'Year1' : IDL.Null,
    'Year2' : IDL.Null,
    'Year3' : IDL.Null,
    'Year4' : IDL.Null,
    'Year5' : IDL.Null,
    'Year6' : IDL.Null,
    'Year7' : IDL.Null,
    'Year8' : IDL.Null,
    'Adhya' : IDL.Null,
    'Madhya' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Artwork = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'artistId' : IDL.Text,
    'level' : ExamLevel,
    'image' : ExternalBlob,
    'isPublic' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Int,
  });
  const Exam = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Int,
    'level' : ExamLevel,
    'score' : IDL.Nat,
  });
  const StudentView = IDL.Record({
    'id' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'name' : IDL.Text,
    'artwork' : IDL.Opt(ExternalBlob),
    'level' : ExamLevel,
    'exams' : IDL.Vec(Exam),
    'guardian' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveAdmission' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getArtwork' : IDL.Func([IDL.Text], [IDL.Opt(Artwork)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPublicArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(StudentView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'promoteStudent' : IDL.Func([IDL.Text, ExamLevel], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchStudentsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentView)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Text], [], []),
    'submitAdmissionForm' : IDL.Func(
        [IDL.Text, IDL.Text, ExamLevel, ExternalBlob],
        [IDL.Text],
        [],
      ),
    'uploadArtwork' : IDL.Func(
        [IDL.Text, IDL.Text, ExamLevel, IDL.Bool, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };