/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artwork {
  'id' : string,
  'title' : string,
  'artistId' : string,
  'level' : ExamLevel,
  'image' : ExternalBlob,
  'isPublic' : boolean,
}
export interface Exam {
  'id' : string,
  'date' : bigint,
  'level' : ExamLevel,
  'score' : bigint,
}
export type ExamLevel = { 'Purna' : null } |
  { 'Year1' : null } |
  { 'Year2' : null } |
  { 'Year3' : null } |
  { 'Year4' : null } |
  { 'Year5' : null } |
  { 'Year6' : null } |
  { 'Year7' : null } |
  { 'Year8' : null } |
  { 'Adhya' : null } |
  { 'Madhya' : null };
export type ExternalBlob = Uint8Array;
export interface Message { 'id' : string, 'content' : string, 'date' : bigint }
export interface StudentView {
  'id' : string,
  'messages' : Array<Message>,
  'name' : string,
  'artwork' : [] | [ExternalBlob],
  'level' : ExamLevel,
  'exams' : Array<Exam>,
  'guardian' : string,
}
export interface UserProfile {
  'studentId' : [] | [string],
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveAdmission' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getArtwork' : ActorMethod<[string], [] | [Artwork]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPublicArtworks' : ActorMethod<[], Array<Artwork>>,
  'getStudent' : ActorMethod<[string], [] | [StudentView]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'promoteStudent' : ActorMethod<[string, ExamLevel], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchStudentsByName' : ActorMethod<[string], Array<StudentView>>,
  'sendMessage' : ActorMethod<[string], undefined>,
  'submitAdmissionForm' : ActorMethod<
    [string, string, ExamLevel, ExternalBlob],
    string
  >,
  'uploadArtwork' : ActorMethod<
    [string, string, ExamLevel, boolean, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];